### ISSUE TITLE
Should underscores be converted by default?

### ISSUE THREAD

**Issue by JayBizzle** [JayBizzle/Safeurl#2]
I just noticed that underscores don't get converted to hyphens by default. Should they?

Any thoughts on this @neilberry001

**Comment by neilberry001** [comment]
Think underscores are acceptable in a url. could be of benefit in some cases to allow a config flag to say underscores => (strip || replace). replace would convert to the separator.  could then run into replacement options for anything other than a space? maybe im going too crazy there though.

Opens a wider discussion on other special characters that aren't acceptable like '*' or will those be stripped?

**Comment by JayBizzle** [comment]
You can specify anything you want if you publish the config file and edit to your own spec

See https://github.com/JayBizzle/Safeurl#options
